const SKILLS={locate:{name:"Localitzar",short:"Busca dades concretes",icon:"01"},infer:{name:"Inferir",short:"Descobrix allò implícit",icon:"02"},integrate:{name:"Interpretar",short:"Connecta les idees",icon:"03"},reflect:{name:"Valorar",short:"Pensa sobre el text",icon:"04"}};
const HINTS={locate:"Torna al text i busca les mateixes paraules o una expressió equivalent.",infer:"Pregunta’t què podem concloure a partir de les pistes, encara que no es diga literalment.",integrate:"Relaciona el principi, el final i les idees que es repetixen.",reflect:"Fixa’t en la intenció, la font o l’efecte que busca l’autor."};
const rawReadings=[
{id:"hort",title:"Un hort damunt de l’institut",type:"Notícia",theme:"Medi ambient",level:2,text:`L’IES Serra Alta ha convertit una terrassa que no s’utilitzava en un hort escolar. El projecte va començar al febrer amb sis jardineres, però en dos mesos ja n’hi havia quinze. L’alumnat de 1r d’ESO planta tomaques, encisams i plantes aromàtiques cada dimarts a l’hora del pati. L’aigua prové d’un depòsit que arreplega la pluja de la teulada.

La professora de Biologia explica que l’hort no és només una activitat ambiental: també servix per a mesurar superfícies en Matemàtiques i escriure un diari d’observació en Valencià. La primera collita es donarà al menjador social del barri.`,qs:[
["locate","On està l’hort escolar?","En una terrassa","Al pati central","Darrere del gimnàs","En un solar pròxim"],["locate","Quin dia treballa l’alumnat a l’hort?","Cada dimarts","Cada dilluns","Els divendres","Només al febrer"],["infer","Per què instal·len un depòsit?","Per aprofitar l’aigua de pluja","Per guardar ferramentes","Per regar amb aigua potable","Per mesurar la terrassa"],["infer","Què indica que el projecte ha crescut?","Han passat de sis a quinze jardineres","La professora és de Biologia","Planten herbes aromàtiques","Treballen durant el pati"],["integrate","Quina idea resumeix millor la notícia?","Un hort escolar combina aprenentatge i ajuda al barri","L’institut vol ampliar el menjador","L’alumnat preferix treballar fora","La pluja ha causat problemes a l’edifici"],["integrate","Quina relació hi ha entre els dos paràgrafs?","El primer descriu l’hort i el segon explica els seus usos","Els dos repetixen la mateixa informació","El segon contradiu el primer","El primer conta el final del projecte"],["reflect","Per què apareix l’opinió de la professora?","Per explicar el valor educatiu del projecte","Per criticar l’horari del pati","Per anunciar una excursió","Per vendre les verdures"],["reflect","Quina dada mostra un compromís social?","La collita es donarà al menjador social","L’hort té quinze jardineres","Es planten tomaques","La terrassa abans no s’utilitzava"]]},
{id:"biblio",title:"La motxilla viatgera",type:"Narració",theme:"Institut",level:2,text:`Quan Núria va arribar a casa, va trobar una motxilla blava al costat de la seua. L’havia agafada per error després d’Educació Física. Dins hi havia un llibre de misteri, una llibreta amb dibuixos de planetes i una entrada per al concert de dissabte.

Núria va mirar el nom escrit a la butxaca: “Yassin, 1r B”. Ja era tard i no podia tornar a l’institut. Va escriure un missatge al grup de classe, però ningú coneixia el seu número. Finalment telefonà a consergeria. L’endemà, Yassin l’esperava a la porta. En recuperar-la, va comprovar primer que l’entrada continuava allí i després va respirar tranquil.`,qs:[
["locate","On troba Núria la motxilla blava?","Al costat de la seua","Al gimnàs","A consergeria","Dins de l’autobús"],["locate","A quin curs pertany Yassin?","A 1r B","A 1r A","A 2n B","A 2n A"],["infer","Per què Yassin mira primer l’entrada?","Té un valor especial perquè la necessita dissabte","Vol saber el preu del concert","Pensa que és de Núria","No recorda on és el llibre"],["infer","Com se sent Yassin al final?","Alleujat","Enfadat","Avorrit","Sorprés per la llibreta"],["integrate","Quin és el problema central?","Núria s’emporta una motxilla que no és seua","Yassin perd una entrada al concert","Núria no vol tornar a classe","El grup no coneix Yassin"],["integrate","Què fa avançar la història cap a la solució?","Núria troba el nom i telefona a consergeria","Yassin dibuixa planetes","Comença la classe d’Educació Física","El concert se celebra dissabte"],["reflect","Per què l’autor enumera el contingut de la motxilla?","Per donar pistes sobre el propietari i allò que li importa","Per demostrar que pesa massa","Per explicar com és l’institut","Per presentar tres assignatures"],["reflect","Quin títol alternatiu encaixa millor?","Una confusió amb final feliç","El concert cancel·lat","Un planeta desconegut","La classe més llarga"]]},
{id:"aigua",title:"Cada got compta",type:"Infografia",theme:"Consum responsable",level:3,text:`REPTE DE SET DIES: ESTALVIEM AIGUA

• Tanca l’aixeta mentre et raspalles les dents: pots estalviar fins a 12 litres cada vegada.
• Una dutxa de cinc minuts gasta aproximadament 50 litres. Un bany pot superar els 150.
• Reutilitza l’aigua de rentar la fruita per a regar les plantes.
• Avisa una persona adulta si detectes una aixeta que degota.

Objectiu de la classe: reduir un 15% el consum durant una setmana. Font: campanya municipal “Aigua de tots”, 2026. Les quantitats són aproximades i poden variar segons la instal·lació.`,qs:[
["locate","Quants litres pot gastar una dutxa de cinc minuts?","Uns 50 litres","Uns 12 litres","Més de 150 litres","Exactament 15 litres"],["locate","Quin és l’objectiu de la classe?","Reduir un 15% el consum","Dutxar-se set vegades","Regar cada dia","Reparar totes les aixetes"],["infer","Per què s’aconsella avisar una persona adulta?","Una fuga necessita una reparació segura","L’alumnat no pot beure aigua","L’aixeta sempre està calenta","Cal mesurar la dutxa"],["infer","Quina acció permet usar la mateixa aigua dues vegades?","Regar amb l’aigua de rentar fruita","Tancar l’aixeta en raspallar-se","Fer una dutxa curta","Avisar d’una gotera"],["integrate","Quina és la finalitat principal?","Proposar accions senzilles per estalviar aigua","Explicar com es construïx una aixeta","Comparar preus de l’aigua","Prohibir els banys a casa"],["integrate","Per què es comparen dutxa i bany?","Per mostrar que una opció pot consumir molt menys","Per dir que els dos gasten igual","Per calcular el preu d’un sabó","Per indicar la temperatura adequada"],["reflect","Què aporta la font municipal?","Ajuda a considerar fiable la informació","Demostra que les xifres són exactes sempre","Convertix el text en una notícia","Indica qui ha guanyat el repte"],["reflect","Per què s’avisa que les quantitats poden variar?","Per presentar les dades amb precisió i prudència","Perquè ningú no faça el repte","Perquè la campanya és antiga","Perquè no es pot mesurar l’aigua"]]},
{id:"robot",title:"El robot que separa residus",type:"Article divulgatiu",theme:"Tecnologia",level:3,text:`Un equip d’estudiants ha programat un robot capaç de diferenciar paper, plàstic i metall. Una càmera observa cada objecte i un programa en compara el color i la forma amb centenars d’exemples. Després, un braç mecànic deposita el residu al contenidor corresponent.

En les primeres proves, el robot encertava set de cada deu objectes. Els errors apareixien sobretot amb envasos bruts o aixafats. L’equip va afegir noves imatges al programa i l’encert va pujar al 89%. Tot i la millora, els creadors recorden que la tecnologia no substituïx la responsabilitat de reduir i reutilitzar.`,qs:[
["locate","Quins materials diferencia el robot?","Paper, plàstic i metall","Vidre, fusta i tela","Només plàstic","Paper i aliments"],["locate","A quin percentatge arriba després de millorar-lo?","Al 89%","Al 70%","Al 100%","Al 19%"],["infer","Per què fallen els envasos aixafats?","La forma ja no s’assembla tant als exemples","Pesaven massa per al braç","La càmera no detecta colors","Eren tots de metall"],["infer","Què va permetre augmentar els encerts?","Afegir més exemples visuals","Canviar els contenidors","Eliminar la càmera","Usar només objectes nets"],["integrate","Quin procés seguix el robot?","Observa, compara i classifica","Pesa, neteja i ven","Arreplega, trenca i crema","Pregunta, espera i etiqueta"],["integrate","Quina és la idea global?","La tecnologia ajuda a reciclar, però no elimina la responsabilitat personal","Els robots ja no cometen errors","Reciclar depén només de les càmeres","Els estudiants volen substituir els contenidors"],["reflect","Per què s’inclouen les dades del 70% i el 89%?","Per mostrar una millora mesurable","Per comparar dos robots diferents","Per indicar el preu del projecte","Per calcular els residus totals"],["reflect","Quina afirmació respecta el punt de vista dels creadors?","Primer hem de reduir i reutilitzar; el robot és una ajuda","El robot farà innecessari separar residus","La tecnologia resol per si sola el problema","Només els envasos nets es poden reciclar"]]},
{id:"ruta",title:"Ruta segura amb bicicleta",type:"Instruccions",theme:"Mobilitat",level:2,text:`ABANS D’EIXIR
1. Comprova que les rodes tinguen aire i que els frens funcionen.
2. Ajusta’t el casc: no ha de moure’s ni tapar-te els ulls.
3. Tria carrils bici o carrers tranquils sempre que siga possible.

DURANT EL TRAJECTE
Senyalitza els girs amb el braç, mantín una distància prudent respecte dels cotxes aparcats i no uses auriculars. Si has de mirar el mapa, para en un lloc segur. De nit, encén els llums davanter i posterior. Arribar dos minuts abans no compensa posar-se en risc.`,qs:[
["locate","Què cal revisar en les rodes?","Que tinguen aire","Que siguen noves","Que siguen blaves","Que no toquen el terra"],["locate","Quan s’han d’encendre els llums?","De nit","Només quan plou","Al carril bici","Abans de frenar"],["infer","Per què no convé usar auriculars?","Poden impedir sentir el trànsit","Fan anar més lenta la bicicleta","Gasten la bateria dels llums","No caben sota el casc"],["infer","Què s’ha de fer si cal consultar el mapa?","Parar en un lloc segur","Circular més de pressa","Traure el mòbil amb una mà","Demanar pas als cotxes"],["integrate","Com s’organitza el text?","En preparació i conducta durant el trajecte","En problemes i solucions mecàniques","En rutes llargues i curtes","En normes per a cotxes i vianants"],["integrate","Quina idea connecta totes les recomanacions?","Reduir riscos abans i durant el viatge","Arribar abans que els altres","Aprendre a reparar una bicicleta","Triar sempre el camí més curt"],["reflect","Què vol dir l’última frase?","La rapidesa no justifica actuar sense seguretat","Dos minuts sempre són suficients","Cal eixir exactament dos minuts abans","Els trajectes curts no tenen risc"],["reflect","Per què els verbs estan en imperatiu?","Per donar instruccions directes al lector","Per contar una experiència passada","Per expressar dubtes","Per descriure un paisatge"]]},
{id:"lluna",title:"Nit d’observació",type:"Correu electrònic",theme:"Ciència",level:3,text:`Assumpte: Canvi d’hora — observació de la Lluna

Hola, famílies,

La previsió indica que els núvols desapareixeran més tard del que esperàvem. Per això, l’activitat de divendres començarà a les 21.30, mitja hora després de l’hora anunciada. Ens trobarem a la porta nord del poliesportiu. Porteu roba d’abric i, si en teniu, uns prismàtics. El centre facilitarà tres telescopis; no cal comprar cap material.

Si a les 19.00 continua plovent, enviarem un missatge per ajornar l’activitat. Consulteu el correu abans d’eixir.

Departament de Física i Química`,qs:[
["locate","A quina hora començarà l’activitat?","A les 21.30","A les 19.00","A les 21.00","A les 22.30"],["locate","On es trobarà el grup?","A la porta nord del poliesportiu","Al laboratori","A l’entrada de l’institut","A la plaça del poble"],["infer","Per què canvia l’hora?","S’espera que els núvols desapareguen més tard","Els telescopis arribaran tard","El poliesportiu tanca prompte","Les famílies ho han demanat"],["infer","Quan és especialment important revisar el correu?","Abans d’eixir si el temps és inestable","Quan ja haja acabat l’activitat","Només a les 21.30","Després de comprar prismàtics"],["integrate","Quina informació és opcional?","Portar prismàtics propis","Dur roba d’abric","Consultar el correu","Anar a la porta nord"],["integrate","Quina és la funció del segon paràgraf breu?","Explicar com se sabrà si s’ajorna","Canviar el lloc de trobada","Demanar material nou","Descriure la Lluna"],["reflect","Per què s’aclarix que no cal comprar material?","Per evitar una despesa innecessària","Perquè no s’usaran telescopis","Per prohibir portar prismàtics","Perquè l’activitat serà de dia"],["reflect","El to del correu és principalment...","clar i preventiu","humorístic i misteriós","crític i agressiu","publicitari i exagerat"]]},
{id:"videojoc",title:"Una pausa també és jugar millor",type:"Article d’opinió",theme:"Videojocs",level:4,text:`Quan una partida es complica, moltes persones insistixen sense parar. Sembla lògic: com més intents, més possibilitats d’aconseguir-ho. Però després d’una estona llarga, l’atenció baixa i repetim els mateixos errors.

Fer una pausa curta no és rendir-se. Alçar-se, beure aigua o mirar lluny de la pantalla ajuda a descansar la vista i a tornar amb una estratègia nova. Això no significa que existisca un temps perfecte per a tothom. Cada persona i cada joc són diferents. La clau és reconéixer quan ja no estem decidint bé i parar abans que la frustració trie per nosaltres.`,qs:[
["locate","Què pot passar després de jugar molta estona?","Baixa l’atenció","El joc canvia sol","Augmenta sempre l’encert","La pantalla es fa més gran"],["locate","Quina acció proposa el text durant una pausa?","Beure aigua","Començar una altra partida","Comprar un comandament","Apagar internet"],["infer","Què significa que “la frustració trie per nosaltres”?","Que actuem impulsivament i decidim pitjor","Que el joc pren decisions automàtiques","Que una altra persona juga","Que la partida s’ha acabat"],["infer","Per què una pausa pot millorar el resultat?","Permet recuperar l’atenció i canviar d’estratègia","Garantix superar qualsevol nivell","Fa que els rivals abandonen","Allarga la duració de la pantalla"],["integrate","Quina tesi defensa l’autor?","Parar a temps pot ajudar a jugar millor","Cal abandonar els videojocs difícils","Totes les pauses han de durar igual","Com més intents seguits, millor"],["integrate","Quin contrast estructura el text?","Insistir sense descans davant de parar amb criteri","Jugar a soles davant de jugar en equip","Jocs nous davant de jocs antics","Pantalles grans davant de menudes"],["reflect","Per què l’autor diu que no hi ha un temps perfecte?","Per reconéixer que les necessitats varien","Per evitar donar cap consell","Perquè no es poden mesurar els minuts","Per defensar partides infinites"],["reflect","Quina evidència reforçaria més l’opinió?","Un estudi sobre atenció abans i després d’una pausa","Una llista dels jocs més venuts","Una foto d’un comandament","El preu mitjà d’una consola"]]},
{id:"mur",title:"El mural que canviava cada dia",type:"Narració",theme:"Convivència",level:4,text:`Dilluns, el mur del pati aparegué cobert de figures geomètriques. Dimarts, algú hi havia afegit un bosc. Dimecres, entre els arbres ja corria un riu blau. Ningú sabia qui pintava després de classe.

Alba volia descobrir-ho i es va quedar amagada darrere d’una columna. Quan el pati es buidà, va veure arribar Omar amb una caixa de pinzells. Abans que ella poguera parlar, també aparegueren Mei, Joan i Sara. Cadascú portava un color. No era el secret d’una sola persona, sinó un acord del grup de mediació per transformar un espai on sovint hi havia discussions. Alba guardà el mòbil: ja no volia gravar-los, sinó ajudar-los.`,qs:[
["locate","Què apareix al mural dimecres?","Un riu blau","Una ciutat","Un pont roig","Un grup d’animals"],["locate","On s’amaga Alba?","Darrere d’una columna","Dins d’una aula","Al costat del mur","En el gimnàs"],["infer","Per què cada alumne porta un color?","Treballen junts en el mateix projecte","No volen compartir els pinzells","Pinten murals diferents","Han oblidat la caixa"],["infer","Per què Alba guarda el mòbil?","Canvia de curiosa observadora a participant","La bateria s’ha acabat","No pot fer fotos al pati","Vol telefonar a casa"],["integrate","Què descobrix Alba realment?","El mural és una iniciativa col·lectiva de convivència","Omar pinta tot el mural a soles","El grup vol ocultar una discussió","El mur es pinta automàticament"],["integrate","Com evoluciona el mural?","Va incorporant elements al llarg de tres dies","Canvia completament cada hora","Es fa més menut cada dia","Perd tots els colors dimecres"],["reflect","Quin efecte produïx retardar l’explicació del misteri?","Manté la curiositat fins al final","Fa impossible entendre el text","Demostra que Alba ja ho sabia","Elimina el conflicte inicial"],["reflect","Quin tema expressa millor el relat?","La col·laboració pot transformar un espai compartit","Els secrets sempre provoquen problemes","Els mòbils impedixen fer amistats","Pintar és una activitat individual"]]},
{id:"micro",title:"Què són els microplàstics?",type:"Text expositiu",theme:"Ciència",level:4,text:`Els microplàstics són fragments de plàstic de menys de cinc mil·límetres. Alguns es fabriquen ja molt menuts; altres apareixen quan objectes més grans, com bosses o botelles, es trenquen per l’acció del sol i de les ones.

S’han trobat en rius, oceans, sòls i fins i tot en l’aire. Estudiar-ne els efectes és difícil perquè tenen mides i composicions molt diferents. La comunitat científica continua investigant com afecten els ecosistemes i la salut humana. Mentrestant, reduir els productes d’un sol ús i evitar abandonar residus impedix que més plàstic arribe al medi.`,qs:[
["locate","Quina mida tenen els microplàstics?","Menys de cinc mil·límetres","Més de cinc centímetres","Exactament un mil·límetre","La mida d’una botella"],["locate","On se n’han trobat?","En aigua, sòl i aire","Només als oceans","Només en ciutats","Exclusivament en aliments"],["infer","Per què és difícil estudiar-ne els efectes?","No tots tenen la mateixa mida ni composició","No es poden trobar al medi","Desapareixen durant el dia","Sempre provenen de botelles"],["infer","Com pot el sol afavorir que se’n formen?","Degrada objectes de plàstic grans","Els convertix en metall","Els fa tornar a la fàbrica","N’augmenta el pes"],["integrate","Quina estructura seguix el text?","Definició, presència, dificultat i prevenció","Problema, personatges i desenllaç","Opinió, rèplica i acord","Instruccions numerades"],["integrate","Quina idea principal integra els dos paràgrafs?","Són fragments estesos que encara s’estudien i convé previndre","Tots els microplàstics es fabriquen menuts","La ciència ja coneix tots els efectes","Només les ones originen microplàstics"],["reflect","Per què apareix “continua investigant”?","Per mostrar que encara hi ha preguntes obertes","Per negar que existisquen microplàstics","Per afirmar que tot està resolt","Per recomanar deixar de previndre"],["reflect","Quina font seria més adequada per ampliar la informació?","Un institut públic d’investigació marina","Un anunci d’una botella de plàstic","Un comentari anònim sense fonts","Un catàleg de joguets"]]},
{id:"festival",title:"Festival de pati",type:"Cartell",theme:"Música",level:2,text:`FESTIVAL DE PATI — DIJOUS 22 D’OCTUBRE

11.05  Grup de percussió · escenari central
11.20  Micro obert · racó de la biblioteca
11.35  Duo de guitarres · escenari central
11.50  Cor de 1r d’ESO · porxe

Per participar en el micro obert, inscriu-te abans de dimarts a la biblioteca. Cada actuació pot durar un màxim de tres minuts. En cas de pluja, totes les activitats es traslladaran al gimnàs i començaran a la mateixa hora. Entrada lliure per a l’alumnat del centre.`,qs:[
["locate","A quina hora actua el duo de guitarres?","A les 11.35","A les 11.20","A les 11.05","A les 11.50"],["locate","On s’ha de fer la inscripció?","A la biblioteca","Al gimnàs","Al porxe","A consergeria"],["infer","Què canvia si plou?","El lloc de totes les actuacions","L’orde de les actuacions","La duració del festival","El dia del festival"],["infer","Qui necessita actuar amb especial brevetat?","Qui participe en el micro obert","El cor de 1r","El duo de guitarres","El grup de percussió"],["integrate","Quina actuació compartix lloc amb la percussió?","El duo de guitarres","El micro obert","El cor de 1r","Cap altra actuació"],["integrate","Què combina el cartell?","Un horari i condicions de participació","Una entrevista i una notícia","Un mapa i una narració","Una recepta i un anunci"],["reflect","Per què es manté l’hora si plou?","Perquè només s’ha previst canviar l’espai","Perquè el gimnàs està sempre buit","Perquè no es pot avisar l’alumnat","Perquè les actuacions duren menys"],["reflect","Quina informació falta per a convidar famílies?","Si també poden entrar persones de fora del centre","El nom del festival","La data de l’activitat","El lloc del micro obert"]]},
{id:"cova",title:"La cova de les petjades",type:"Reportatge",theme:"Patrimoni",level:5,text:`Durant dècades, les marques de la Cova Fosca es van considerar simples irregularitats de la roca. L’any passat, un equip d’arqueòlogues les va fotografiar amb llum lateral i va observar formes repetides: dits, palmells i talons. La datació dels sediments situa les petjades fa uns 7.000 anys.

L’equip evita afirmar encara quantes persones hi entraren. Algunes marques podrien pertànyer al mateix individu i altres s’han deteriorat amb la humitat. Per protegir el jaciment, la ubicació exacta no s’ha fet pública. El museu local prepara una reproducció digital perquè la ciutadania puga explorar la cova sense posar-la en perill.`,qs:[
["locate","Com es van fotografiar les marques?","Amb llum lateral","Amb llum de colors","Des d’un satèl·lit","Sota l’aigua"],["locate","De quan són aproximadament les petjades?","De fa 7.000 anys","De fa 700 anys","De l’any passat","De fa 70.000 anys"],["infer","Per què no es publica el lloc exacte?","Per evitar danys al jaciment","Perquè ningú sap on està","Per vendre entrades més cares","Perquè la cova ha desaparegut"],["infer","Per què no poden calcular encara el nombre de persones?","Una persona pot haver deixat diverses marques","No han trobat cap marca","Les fotos no tenen llum","Els sediments són recents"],["integrate","Quin canvi de coneixement presenta el reportatge?","De considerar les marques naturals a identificar possibles petjades","De conéixer la cova a perdre-la","De publicar el lloc a obrir-lo lliurement","De datar la roca a negar-ne l’antiguitat"],["integrate","Com es combina divulgació i protecció?","Amb una reproducció digital visitable","Amb l’obertura total de la cova","Amb l’eliminació de la humitat","Amb la venda de fotografies"],["reflect","Què mostra prudència científica?","L’equip evita donar una xifra sense proves suficients","La cova rep un nom atractiu","El museu prepara una activitat","Les marques es fotografien"],["reflect","Quina evidència reforça que són petjades?","La repetició de formes de dits, palmells i talons","El fet que la cova siga fosca","La proximitat del museu","La presència d’humitat"]]},
{id:"son",title:"Dormir no és perdre el temps",type:"Entrevista",theme:"Salut",level:4,text:`—Per què costa tant alçar-se alguns matins?
—Durant l’adolescència, el rellotge intern tendix a retardar-se. Si, a més, usem pantalles fins tard, el cervell rep senyals que dificulten adormir-se.

—Recuperem el son dormint molt el cap de setmana?
—Pot alleujar el cansament, però canviar molt els horaris fa més difícil tornar a la rutina. Sol funcionar millor mantindre una hora semblant per a gitar-se i alçar-se.

—Quin primer canvi recomanaria?
—Preparar el final del dia: llum més baixa, tasques tranquil·les i el mòbil fora del llit. No cal fer-ho perfecte; cal repetir-ho.`,qs:[
["locate","Què pot dificultar adormir-se?","Usar pantalles fins tard","Llegir amb llum baixa","Alçar-se sempre igual","Fer una tasca tranquil·la"],["locate","Quin objecte recomana deixar fora del llit?","El mòbil","El despertador","Un llibre","El coixí"],["infer","Per què dormir molt dissabte no resol sempre el problema?","Un gran canvi d’horari dificulta tornar a la rutina","El cap de setmana té menys hores","Dormir de dia està prohibit","El cansament desapareix només dilluns"],["infer","Què vol dir “no cal fer-ho perfecte; cal repetir-ho”?","La constància importa més que un dia ideal","Els consells no servixen","Cal dormir exactament igual","No s’ha de canviar res"],["integrate","Quin consell reunix totes les respostes?","Crear una rutina nocturna regular","Dormir només el cap de setmana","Eliminar totes les pantalles de casa","Alçar-se cada dia més tard"],["integrate","Quina funció té la primera pregunta?","Introduir una causa pròpia de l’adolescència","Criticar l’ús dels despertadors","Explicar el cap de setmana","Definir què és una entrevista"],["reflect","Per què el format de preguntes i respostes és útil?","Organitza dubtes habituals i respostes directes","Fa que la informació siga menys clara","Evita donar recomanacions","Demostra que només parla una persona"],["reflect","Quina dada caldria afegir per valorar millor la font?","La professió i especialitat de la persona entrevistada","La marca del seu mòbil","El lloc on dorm","El seu dia preferit"]]},
{id:"algoritme",title:"Per què em recomana això?",type:"Article divulgatiu",theme:"Xarxes",level:5,text:`Quan una plataforma et suggerix un vídeo, no l’ha triat a l’atzar. Un algoritme compara accions com el temps de visualització, els “m’agrada” o els temes que has buscat. Amb eixes pistes calcula què podria mantindre la teua atenció.

La recomanació pot ser útil per trobar contingut nou, però també pot repetir idees semblants i reduir la varietat del que veus. Per això convé buscar de manera activa, revisar l’historial i no confondre “m’apareix molt” amb “és cert”. L’algoritme prediu interés; no comprova necessàriament la qualitat ni la veracitat.`,qs:[
["locate","Quina acció pot usar l’algoritme com a pista?","El temps de visualització","La bateria del dispositiu","La mida de la pantalla","El volum dels altaveus"],["locate","Què prediu principalment l’algoritme?","L’interés de l’usuari","La veritat d’una notícia","La qualitat educativa","La intenció de l’autor"],["infer","Per què pot reduir-se la varietat?","Es recomanen continguts semblants als ja vistos","Tots els vídeos duren igual","La plataforma elimina l’historial","L’usuari no pot buscar"],["infer","Quin risc hi ha en “m’apareix molt”?","Prendre la repetició com una prova de veritat","Veure contingut massa curt","Perdre els botons de la pantalla","Canviar de tema massa sovint"],["integrate","Quina postura adopta el text?","Reconeix la utilitat i advertix dels límits","Defensa eliminar tots els algoritmes","Afirma que les recomanacions sempre mentixen","Explica només avantatges"],["integrate","Quina acció ajuda a ampliar perspectives?","Buscar activament altres fonts i temes","Acceptar només el primer vídeo","Desactivar el so","Repetir les mateixes cerques"],["reflect","Per què es distingix interés de veracitat?","Perquè una recomanació atractiva pot ser falsa","Perquè tot allò popular és vertader","Perquè l’algoritme escriu notícies","Perquè la veritat depén dels “m’agrada”"],["reflect","Quina pregunta crítica convé fer davant d’un vídeo recomanat?","Qui ho afirma i quines proves aporta?","Quants segons dura?","Té música de fons?","Quin color té la miniatura?"]]},
{id:"mascota",title:"Abans d’adoptar",type:"Guia",theme:"Animals",level:3,text:`Adoptar un animal és una decisió familiar, no un regal sorpresa. Abans d’anar al refugi, cal parlar del temps disponible, les despeses veterinàries i qui s’encarregarà de cada tasca. Un gos, un gat o un conill tenen necessitats diferents; l’espai de casa no és l’únic factor.

Al refugi, el personal pot explicar el caràcter i la història de cada animal. Convé contar amb sinceritat com és la rutina de la família. Així poden orientar una adopció compatible. Els primers dies cal oferir calma i un espai segur: adaptar-se no és immediat. Si apareixen dificultats, demanar ajuda és més responsable que ignorar-les.`,qs:[
["locate","Quines despeses s’han de preveure?","Les veterinàries","Les del refugi escolar","Les d’un viatge","Només les de joguets"],["locate","Qui informa sobre el caràcter de l’animal?","El personal del refugi","Qualsevol visitant","Una botiga pròxima","El veïnat"],["infer","Per què cal explicar la rutina familiar?","Per trobar un animal compatible","Per pagar menys per l’adopció","Per triar només per la mida","Per evitar parlar amb el personal"],["infer","Què implica que adaptar-se “no és immediat”?","L’animal necessita temps i calma","L’animal no aprendrà mai","Cal canviar de casa","No es pot demanar ajuda"],["integrate","Quines dos fases organitzen la guia?","Preparar la decisió i facilitar l’adaptació","Comprar i vendre","Entrenar i competir","Viatjar i tornar"],["integrate","Quin principi resumix el text?","Adoptar exigix informació, acord i responsabilitat","Qualsevol animal s’adapta a qualsevol casa","L’espai és l’únic que importa","Els problemes s’han d’amagar"],["reflect","Per què es rebutja el “regal sorpresa”?","Perquè impedix valorar les responsabilitats entre tots","Perquè els refugis no fan regals","Perquè els animals no poden viatjar","Perquè sempre és massa car"],["reflect","Quina font ampliaria millor aquesta guia?","Una protectora d’animals amb equip veterinari","Un anunci de menjar per a mascotes","Un vídeo sense autor","Un concurs de fotografies"]]},
{id:"rumor",title:"El missatge de les huit",type:"Narració",theme:"Convivència digital",level:5,text:`A les huit en punt, el grup de classe començà a omplir-se de missatges: “Demà no hi ha examen”. La captura semblava procedir del perfil del professor, però el nom apareixia tallat. Algunes persones celebraren la notícia; altres guardaren els apunts.

Irene va observar que la tipografia no coincidia amb la plataforma del centre. Buscà l’avís original i no el trobà. En lloc de reenviar la captura, preguntà al delegat, que escrigué al professor per un canal oficial. Deu minuts després arribà la resposta: l’examen es mantenia. Ningú va descobrir qui havia creat la imatge, però la classe sí que aprengué una regla: la urgència d’un missatge no el fa més fiable.`,qs:[
["locate","Quina informació difonia la captura?","Que no hi hauria examen","Que l’examen canviava d’aula","Que faltava el professor","Que calia portar apunts"],["locate","Quant tarda a arribar la resposta?","Deu minuts","Una hora","Dos minuts","Fins a l’endemà"],["infer","Quina pista fa dubtar Irene?","La tipografia no coincidia","El missatge arribà a les huit","Algunes persones celebraren","El delegat tenia apunts"],["infer","Per què usa el delegat un canal oficial?","Per verificar la informació en una font directa","Per trobar qui va fer la captura","Per ajornar l’examen","Per eliminar el grup de classe"],["integrate","Quin procés seguix Irene?","Detecta una incoherència, busca i verifica","Reenvia, celebra i es desconnecta","Pregunta, inventa i publica","Estudia, protesta i abandona"],["integrate","Quina idea principal deixa el relat?","Cal verificar abans de compartir informació dubtosa","Les captures sempre són falses","Els grups de classe no són útils","Els exàmens mai no s’ajornen"],["reflect","Quin recurs fa versemblant el rumor al principi?","Imita el perfil del professor","Inclou moltes explicacions","Arriba per correu oficial","Mostra el nom complet"],["reflect","Quina frase expressa millor una lectura crítica?","L’aparença i la urgència no substituïxen una font fiable","Si molta gent ho creu, és cert","Un missatge curt no pot ser fals","La primera captura sempre és l’original"]]},
{id:"bosc",title:"Escoltar el bosc",type:"Crònica",theme:"Natura",level:6,text:`El grup va entrar al parc natural amb una norma estranya: durant deu minuts ningú podia parlar. Al principi se sentien només les passes i alguna rialla continguda. Després aparegueren sons que abans quedaven amagats: el colp sec d’un picot, les fulles mogudes per una sargantana, l’aigua d’una séquia llunyana.

En acabar, la guia demanà que cada persona dibuixara un mapa dels sons. Cap mapa era igual. Alguns situaven el picot molt prop; altres ni tan sols l’havien sentit. “El paisatge també depén de l’atenció”, explicà. De tornada, el grup parlava més fluix, com si el silenci continuara formant part de l’excursió.`,qs:[
["locate","Quant dura el silenci inicial?","Deu minuts","Una hora","Cinc minuts","Tota l’excursió"],["locate","Què dibuixa cada persona?","Un mapa dels sons","Una ruta de tornada","Un animal imaginari","Un plànol del centre"],["infer","Per què els mapes són diferents?","Cada persona para atenció a sons diferents","El grup visita llocs diferents","La guia canvia les instruccions","Els sons estan escrits"],["infer","Què indica que tornen parlant més fluix?","L’experiència ha canviat la seua manera d’escoltar","Estan enfadats amb la guia","No recorden la ruta","Tenen prohibit parlar"],["integrate","Com canvia la percepció del grup?","Del soroll propi als detalls de l’entorn","De conéixer el bosc a perdre’s","D’escoltar animals a veure’ls","De dibuixar a fotografiar"],["integrate","Quina idea dona unitat al text?","L’atenció transforma la manera de percebre un lloc","El silenci elimina tots els sons","Tots escoltem exactament igual","Els mapes visuals són més precisos"],["reflect","Què suggerix la frase final “com si el silenci continuara”?","L’activitat els ha deixat una actitud més conscient","La guia encara controla el grup","Ja no volen parlar mai","L’excursió no ha acabat"],["reflect","Per què la guia demana dibuixar i no sols enumerar?","Per representar la posició percebuda dels sons","Per comprovar qui dibuixa millor","Per decorar l’aula","Per calcular la duració del trajecte"]]}
];

let qCounter=0;
const readings=[...rawReadings,...extraReadings].map((r,ri)=>({...r,text:r.text+(readingExtensions[r.id]||""),questions:r.qs.map((x,qi)=>{const [skill,prompt,answer,...distractors]=x;const pos=(ri+qi*3)%4;const options=[...distractors];options.splice(pos,0,answer);qCounter++;return{id:`${r.id}-${qi+1}`,skill,difficulty:Math.max(1,Math.min(6,r.level+(qi>5?1:0))),prompt,options,correct:pos,answer};})}));
const distractorTweaks={
"hort-3":["Per regar amb aigua potable","Per regar sempre amb aigua potable de la xarxa"],"hort-4":["La professora és de Biologia","La professora de Biologia dirigix totes les activitats del pati"],"hort-5":["La pluja ha causat problemes a l’edifici","La pluja ha causat problemes importants a la terrassa de l’edifici"],"hort-6":["Els dos repetixen la mateixa informació","Els dos paràgrafs repetixen les mateixes dades sobre les jardineres"],"hort-7":["Per criticar l’horari del pati","Per criticar que l’horari del pati siga massa curt per a plantar"],"hort-8":["La terrassa abans no s’utilitzava","La terrassa no s’utilitzava abans que començara el projecte escolar"],
"biblio-1":["Dins de l’autobús","Dins de l’autobús, davall del seient que ocupava Núria"],"biblio-3":["Vol saber el preu del concert","Vol comprovar quant va costar l’entrada del concert de dissabte"],"biblio-5":["Yassin perd una entrada al concert","Yassin perd l’entrada i intenta aconseguir-ne una altra per al concert"],"biblio-6":["Comença la classe d’Educació Física","Comença la classe d’Educació Física i l’alumnat deixa les motxilles"],"biblio-7":["Per presentar tres assignatures","Per presentar les tres assignatures preferides de l’amo de la motxilla"],"biblio-8":["El concert cancel·lat","El concert de dissabte que finalment queda cancel·lat"],
"aigua-3":["L’alumnat no pot beure aigua","L’alumnat no pot beure aigua de cap aixeta que estiga degotant"],"aigua-4":["Tancar l’aixeta en raspallar-se","Tancar l’aixeta durant tot el temps que dura el raspallat"],"aigua-5":["Explicar com es construïx una aixeta","Explicar pas a pas com es construïx i es repara una aixeta domèstica"],"aigua-6":["Per indicar la temperatura adequada","Per indicar quina és la temperatura més adequada per a dutxar-se"],"aigua-8":["Perquè no es pot mesurar l’aigua","Perquè és impossible mesurar l’aigua consumida en una casa"],
"robot-1":["Vidre, fusta i tela","Vidre, fusta i diferents tipus de tela de colors"],"robot-3":["La càmera no detecta colors","La càmera deixa de detectar els colors quan els envasos estan bruts"],"robot-4":["Usar només objectes nets","Usar únicament objectes nets, nous i sense cap deformació"],"robot-5":["Pregunta, espera i etiqueta","Pregunta a l’equip, espera una resposta i etiqueta cada residu"],"robot-6":["Els estudiants volen substituir els contenidors","Els estudiants volen substituir tots els contenidors per un sol robot"],"robot-8":["La tecnologia resol per si sola el problema","La tecnologia resol per si sola tot el problema dels residus urbans"],
"ruta-5":["En problemes i solucions mecàniques","En una llista de problemes mecànics i les seues possibles solucions"],"ruta-6":["Aprendre a reparar una bicicleta","Aprendre a reparar qualsevol avaria d’una bicicleta durant el trajecte"],"ruta-7":["Cal eixir exactament dos minuts abans","Cal eixir exactament dos minuts abans per evitar qualsevol perill"],"ruta-8":["Per contar una experiència passada","Per contar una experiència passada del ciclista que escriu la guia"],
"lluna-2":["A l’entrada de l’institut","A l’entrada principal de l’institut, al costat del laboratori"],"lluna-3":["Els telescopis arribaran tard","Els telescopis del centre arribaran més tard del que estava previst"],"lluna-4":["Quan ja haja acabat l’activitat","Quan l’activitat ja haja acabat i el grup torne a casa"],"lluna-5":["Anar a la porta nord","Anar a la porta nord del poliesportiu abans de l’hora indicada"],"lluna-6":["Canviar el lloc de trobada","Canviar el lloc de trobada si el poliesportiu està ocupat"],"lluna-7":["Per prohibir portar prismàtics","Per prohibir que les famílies porten prismàtics o telescopis propis"]};
for(const r of readings)for(const q of r.questions){const t=distractorTweaks[q.id];if(t){const i=q.options.indexOf(t[0]);if(i>=0)q.options[i]=t[1]}}
for(const r of readings)for(const q of r.questions){const replacement=longerDistractors[q.id];if(replacement){const index=q.options.reduce((best,option,i)=>i!==q.correct&&option.length>q.options[best].length?i:best,q.options.findIndex((_,i)=>i!==q.correct));q.options[index]=replacement}}
const defaultState={diagnosticDone:false,level:2,streak:0,totalAnswered:0,mastery:{locate:50,infer:50,integrate:50,reflect:50},history:[],completed:[],lastPromotionAt:0,session:null};
let state=loadState();let view="home";let activity=null;let bankOpen=false;let bankQuery="";let bankType="Totes";let bankPage=0;
function loadState(){try{const saved=JSON.parse(localStorage.getItem("compren-state")||"{}");const loaded={...defaultState,...saved};if(!loaded.diagnosticDone&&loaded.totalAnswered===0)loaded.mastery={...defaultState.mastery};return loaded}catch{return structuredClone(defaultState)}}
function saveState(){localStorage.setItem("compren-state",JSON.stringify(state))}
function esc(s){return String(s).replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[m]))}
function toast(msg){const el=document.querySelector("#toast");el.textContent=msg;el.classList.add("show");setTimeout(()=>el.classList.remove("show"),2200)}
function setView(next,scrollTop=true){view=next;activity=null;document.querySelectorAll(".nav-item").forEach(b=>b.classList.toggle("active",b.dataset.view===next));render();document.querySelector("#app").focus();if(scrollTop)scrollTo({top:0,behavior:"smooth"})}
function skillRows(m=state.mastery){return Object.entries(SKILLS).map(([k,v])=>`<div class="skill-row"><b>${v.name}</b><div class="progress-track"><div class="progress-fill" style="width:${m[k]}%"></div></div><b>${m[k]}%</b></div>`).join("")}
function render(){const app=document.querySelector("#app");if(activity){const readingScroll=app.querySelector(".reading")?.scrollTop||0;app.innerHTML=activityMarkup();app.querySelector(".reading").scrollTop=readingScroll;bindActivity();return}if(view==="home")app.innerHTML=homeMarkup();if(view==="practice")app.innerHTML=practiceMarkup();if(view==="progress")app.innerHTML=progressMarkup();if(view==="teacher")app.innerHTML=teacherMarkup();bindGeneral()}
function homeMarkup(){const next=state.diagnosticDone?"Continuar llegint":"Fer el diagnòstic";const rec=chooseReading();return `<section class="page home-page"><p class="eyebrow">Comprensió escrita · 1r d’ESO</p><h1 class="page-title">Bon dia.</h1><p class="quiet-intro">${state.diagnosticDone?`Hui pots continuar amb ${weakestName().toLowerCase()}.`:'Comença amb una prova breu i prepararem les lectures per a tu.'}</p><article class="focus-card"><div><span class="tag">${state.diagnosticDone?'Recomanada per a tu':'Primer pas'}</span><h2>${state.diagnosticDone?esc(rec.title):'Descobrim com lliges'}</h2><p>${state.diagnosticDone?`${rec.type} · Nivell ${rec.level} · ${rec.questions.length} preguntes`:'3 textos · 24 preguntes · al teu ritme'}</p></div><button class="btn btn-primary" data-action="${state.diagnosticDone?'adaptive':'diagnostic'}">${next}</button></article><div class="home-quick"><div><span class="quick-label">Nivell</span><strong>${state.diagnosticDone?state.level:'—'}</strong></div><div><span class="quick-label">Pròxima habilitat</span><strong>${state.diagnosticDone?weakestName():'Després del diagnòstic'}</strong></div><button class="quiet-link" data-action="open-library">Explorar les ${readings.length} lectures</button></div></section>`}
function practiceMarkup(){const rec=chooseReading();return `<section class="page practice-page"><p class="eyebrow">Practica</p><h1 class="page-title">Una lectura per a tu</h1><p class="quiet-intro">${state.diagnosticDone?`Ara treballarem ${weakestName().toLowerCase()} amb un text adequat al teu punt de partida.`:'Pots explorar el banc. Per a rebre una recomanació ajustada, fes primer el diagnòstic.'}</p><article class="focus-card"><div><span class="tag">Nivell ${rec.level} · ${rec.type}</span><h2>${esc(rec.title)}</h2><p>${esc(rec.theme)} · ${rec.questions.length} preguntes · ${wordCount(rec.text)} paraules</p></div><button class="btn btn-primary" data-action="adaptive">Començar</button></article><div class="library-entry"><div><h2>Biblioteca</h2><p>${readings.length} lectures de diferents tipus i nivells</p></div><button class="btn btn-secondary" data-action="toggle-bank" aria-expanded="${bankOpen}" aria-controls="bank-panel">${bankOpen?'Amagar lectures':'Veure totes les lectures'}</button></div>${bankOpen?bankMarkup():''}</section>`}
function categoryFor(r){if(["Narració","Conte","Diari personal","Crònica"].includes(r.type))return "Narratius";if(["Article d’opinió","Ressenya","Dos textos d’opinió"].includes(r.type))return "Opinió";if(r.type==="Dos textos")return "Dos textos";if(["Instruccions","Correu electrònic","Cartell","Guia","Horari i avís","Guia de consum","Acta d’assemblea","Anunci cultural","Recepta i consells","Carta personal"].includes(r.type))return "Funcionals";return "Informatius"}
function bankMarkup(){const types=["Totes","Narratius","Informatius","Funcionals","Opinió","Dos textos"];const normalized=bankQuery.trim().toLocaleLowerCase("ca");const filtered=readings.filter(r=>(bankType==="Totes"||categoryFor(r)===bankType)&&(!normalized||`${r.title} ${r.theme} ${r.type}`.toLocaleLowerCase("ca").includes(normalized)));const pages=Math.max(1,Math.ceil(filtered.length/8));bankPage=Math.min(bankPage,pages-1);return `<div id="bank-panel" class="bank-panel"><div class="bank-controls"><label class="search-wrap"><span class="sr-only">Busca una lectura</span><input id="bank-search" type="search" placeholder="Busca per títol o tema" value="${esc(bankQuery)}"></label><label class="select-wrap"><span class="sr-only">Tipus de text</span><select id="bank-type">${types.map(t=>`<option ${t===bankType?'selected':''}>${esc(t)}</option>`).join('')}</select></label></div><p class="bank-count">${filtered.length} ${filtered.length===1?'lectura':'lectures'}</p><div class="bank-list">${filtered.slice(bankPage*8,bankPage*8+8).map(r=>`<button class="bank-row" data-reading="${r.id}" aria-label="Llegir ${esc(r.title)}"><span><strong>${esc(r.title)}</strong><small>${esc(r.type)} · ${esc(r.theme)}</small></span><span class="bank-row-end"><span class="bank-row-meta">Nivell ${r.level}<br>${wordCount(r.text)} paraules</span><span class="bank-row-open" aria-hidden="true">Llegir</span></span></button>`).join('')||'<p class="bank-empty">No hi ha lectures amb aquests filtres.</p>'}</div><div class="bank-pages"><button class="btn btn-secondary" data-action="prev-page" ${bankPage===0?'disabled':''}>Anterior</button><span>${bankPage+1} de ${pages}</span><button class="btn btn-secondary" data-action="next-page" ${bankPage>=pages-1?'disabled':''}>Següent</button></div></div>`}
function wordCount(s){return s.trim().split(/\s+/).length}
function progressMarkup(){if(!state.diagnosticDone)return `<section class="page home-page"><p class="eyebrow">El meu progrés</p><h1 class="page-title">Comencem pel punt de partida</h1><p class="quiet-intro">Quan acabes el diagnòstic, ací veuràs les habilitats que domines i què pots practicar després.</p><button class="btn btn-primary" data-action="diagnostic">Fer el diagnòstic</button></section>`;const total=state.totalAnswered;return `<section class="page"><p class="eyebrow">Progrés personal</p><h1 class="page-title">El teu recorregut lector</h1><div class="grid3" style="margin-top:22px"><article class="card"><p>Nivell intern</p><div class="metric">${state.level} · ${levelName(state.level)}</div></article><article class="card"><p>Preguntes treballades</p><div class="metric">${total}</div></article><article class="card"><p>Lectures completades</p><div class="metric">${new Set(state.completed).size}</div></article></div><article class="card" style="margin-top:18px"><div class="section-head" style="margin:0 0 12px"><div><p class="eyebrow">Mapa d’habilitats</p><h2>Què ja domines?</h2></div></div><div class="skill-list">${skillRows()}</div></article><div class="level-map">${[1,2,3,4,5,6].map(n=>`<div class="level-node ${n===state.level?'active':''}"><strong>${n}</strong><span>${levelName(n)}</span></div>`).join("")}</div><div class="callout" style="margin-top:22px"><strong>Pròxim objectiu:</strong> ${nextGoal()} Amb dos resultats sòlids seguits, la dificultat pujarà de manera gradual.</div></section>`}
function teacherMarkup(){const students=[["Aina R.",4,91,78,66,52],["Biel M.",3,86,61,54,39],["Carla S.",5,94,83,79,68],["Dídac P.",2,73,44,36,31],["Eva T.",4,88,72,69,49],["Ferran L.",3,79,58,47,34]];return `<section class="page"><p class="eyebrow">Vista docent · 1r ESO B</p><h1 class="page-title">On necessita ajuda el grup?</h1><div class="teacher-summary" style="margin-top:22px"><article class="card"><h3>Dificultat prioritària: inferències causals</h3><p>11 de 24 alumnes confonen una dada del text amb la causa que explica una acció. La recomanació és treballar “què passa just abans?” en textos narratius breus.</p><div class="skill-list">${skillRows({locate:84,infer:59,integrate:55,reflect:41})}</div></article><article class="card"><p>Distribució del grup</p><div class="donut"></div><p style="text-align:center">24 alumnes · sense rànquing</p></article></div><div class="table-wrap"><table><thead><tr><th>Alumne</th><th>Nivell</th><th>Localitza</th><th>Infereix</th><th>Interpreta</th><th>Valora</th><th>Seguiment</th></tr></thead><tbody>${students.map((s,i)=>`<tr><td><b>${s[0]}</b></td><td>${s[1]}</td><td>${s[2]}%</td><td>${s[3]}%</td><td>${s[4]}%</td><td>${s[5]}%</td><td class="status ${i===3?'warn':''}">${i===3?'Revisar':'En curs'}</td></tr>`).join("")}</tbody></table></div><p style="color:var(--muted);margin-top:14px">Dades demostratives per validar la interfície. La versió amb grups reals requerirà identificació i emmagatzematge segur.</p></section>`}
function diagnosticIntro(){return `<section class="page"><div class="diagnostic-intro"><article class="card"><p class="eyebrow">Punt de partida</p><h1 class="page-title">Descobrim com lliges</h1><p class="lead">Llegiràs tres textos diferents i respondràs 24 preguntes. No és una nota: ens servirà per preparar el teu itinerari.</p><ul class="checklist"><li>Pots avançar al teu ritme.</li><li>En el diagnòstic no hi ha pistes.</li><li>Duració aproximada: 20 minuts.</li><li>Al final veuràs fortaleses i pròxims passos.</li></ul><button class="btn btn-primary" data-action="start-diagnostic">Començar</button></article><article class="card mini-preview"><p>Analitzarem quatre habilitats</p><h2>Buscar · Inferir<br>Interpretar · Valorar</h2><p>Cada resposta ajuda a construir un perfil més útil que una nota única.</p></article></div></section>`}
function startDiagnostic(){const questions=readings.slice(0,3).flatMap(r=>r.questions.map(q=>({...q,reading:r})));activity={mode:"diagnostic",questions,index:0,selected:null,attempts:0,feedback:null,results:[]};render()}
function startReading(id,adaptive=false){const r=id?readings.find(x=>x.id===id):chooseReading();if(!r)return;const weak=weakestKey();let qs=[...r.questions];if(adaptive)qs.sort((a,b)=>Number(b.skill===weak)-Number(a.skill===weak)||r.questions.indexOf(a)-r.questions.indexOf(b));activity={mode:"practice",reading:r,questions:qs.map(q=>({...q,reading:r})),index:0,selected:null,attempts:0,feedback:null,results:[]};render();scrollTo({top:0,behavior:"smooth"})}
function chooseReading(){const recent=state.history.slice(-4).map(x=>x.reading);const lastType=readings.find(r=>r.id===recent.at(-1))?.type;return [...readings].sort((a,b)=>{const score=r=>Math.abs(r.level-state.level)*5+(state.completed.includes(r.id)?12:0)+(recent.includes(r.id)?8:0)+(r.type===lastType?2:0);return score(a)-score(b)||a.id.localeCompare(b.id)})[0]}
function activityMarkup(){const q=activity.questions[activity.index],r=q.reading||activity.reading,pct=Math.round(activity.index/activity.questions.length*100);return `<section class="page activity-page"><div class="window"><div class="activity-top"><button class="quiet-link" data-action="exit-activity" aria-label="${activity.mode==='diagnostic'?'Eixir del diagnòstic':'Tornar a la biblioteca'}">${activity.mode==='diagnostic'?'Eixir del diagnòstic':'Biblioteca'}</button><div class="question-count">${activity.index+1} / ${activity.questions.length}</div><div class="activity-progress"><div class="progress-track"><div class="progress-fill" style="width:${pct}%"></div></div></div></div><div class="activity-grid"><article class="reading"><div class="meta-row"><span class="tag">${esc(r.type)}</span><span class="tag">Nivell ${r.level}</span></div><h1>${esc(r.title)}</h1><div class="reading-body">${esc(r.text)}</div></article><article class="question"><p class="eyebrow">${SKILLS[q.skill].name} · dificultat ${q.difficulty}</p><h2>${esc(q.prompt)}</h2><div class="options">${q.options.map((o,i)=>`<button class="option ${activity.selected===i?'selected':''}" data-option="${i}"><span class="letter">${"ABCD"[i]}</span><span>${esc(o)}</span></button>`).join("")}</div>${activity.feedback?`<div class="feedback ${activity.feedback.good?'good':''}"><strong>${activity.feedback.title}</strong>${esc(activity.feedback.text)}</div>`:""}<div class="question-actions"><span></span><button class="btn btn-primary" data-action="check" ${activity.selected===null&&!activity.feedback?.good?'disabled':''}>${activity.feedback?.good||activity.attempts>=2?'Continuar':'Comprovar'}</button></div></article></div></div></section>`}
function bindActivity(){document.querySelectorAll("[data-option]").forEach(b=>b.onclick=()=>{if(activity.feedback?.good||activity.attempts>=2)return;activity.selected=Number(b.dataset.option);document.querySelectorAll("[data-option]").forEach(x=>x.classList.toggle("selected",x===b));document.querySelector('[data-action="check"]').disabled=false});document.querySelector('[data-action="exit-activity"]').onclick=()=>{const wasDiagnostic=activity.mode==='diagnostic';activity=null;if(wasDiagnostic)setView('home');else openLibrary()};document.querySelector('[data-action="check"]').onclick=checkAnswer}
function checkAnswer(){const q=activity.questions[activity.index];if(activity.feedback?.good||activity.attempts>=2){nextQuestion();return}if(activity.mode==="diagnostic"){activity.results.push({skill:q.skill,ok:activity.selected===q.correct,attempts:1});nextQuestion();return}activity.attempts++;const ok=activity.selected===q.correct;if(ok){activity.feedback={good:true,title:"Molt bé!",text:` ${q.answer}`};activity.results.push({skill:q.skill,ok:true,attempts:activity.attempts});render();return}if(activity.attempts===1){activity.feedback={good:false,title:"Encara no.",text:` ${HINTS[q.skill]} Tens un segon intent.`};activity.selected=null;render();return}activity.feedback={good:false,title:"La resposta era:",text:` ${q.answer}`};activity.results.push({skill:q.skill,ok:false,attempts:2});render()}
function nextQuestion(){if(activity.index<activity.questions.length-1){activity.index++;activity.selected=null;activity.attempts=0;activity.feedback=null;render()}else finishActivity()}
function finishActivity(){const results=activity.results;const score=Math.round(results.reduce((sum,x)=>sum+(x.ok?(x.attempts===1?1:.5):0),0)/results.length*100);if(activity.mode==="diagnostic"){const grouped={locate:[],infer:[],integrate:[],reflect:[]};results.forEach(x=>grouped[x.skill].push(x.ok?1:0));Object.keys(grouped).forEach(k=>state.mastery[k]=Math.round(grouped[k].reduce((a,b)=>a+b,0)/grouped[k].length*100));state.level=diagnosticLevel(state.mastery);state.diagnosticDone=true;state.totalAnswered+=results.length;saveState();activity=null;document.querySelector("#app").innerHTML=resultMarkup(score,true);bindGeneral();registerWebMCP();return}const r=activity.reading;results.forEach(x=>{const old=state.mastery[x.skill];state.mastery[x.skill]=Math.round(old*.82+(x.ok?(x.attempts===1?100:70):20)*.18)});state.totalAnswered+=results.length;state.completed.push(r.id);state.history.push({date:new Date().toISOString(),reading:r.id,score});const recent=state.history.slice(-2);if(state.history.length-(state.lastPromotionAt||0)>=2&&recent.length===2){if(recent.every(x=>x.score>=80)&&Object.values(state.mastery).filter(x=>x>=70).length>=3){state.level=Math.min(6,state.level+1);state.lastPromotionAt=state.history.length}else if(recent.every(x=>x.score<=40)){state.level=Math.max(1,state.level-1);state.lastPromotionAt=state.history.length}}saveState();activity=null;document.querySelector("#app").innerHTML=resultMarkup(score,false);bindGeneral();registerWebMCP()}
function resultMarkup(score,diagnostic){return `<section class="page"><article class="card" style="max-width:800px;margin:auto"><p class="eyebrow">${diagnostic?'Diagnòstic complet':'Sessió completada'}</p><h1 class="page-title">${diagnostic?`El teu punt de partida és el nivell ${state.level}`:`${score}% de domini`}</h1><p class="lead">${diagnostic?'Ja tenim un mapa inicial. Les activitats següents reforçaran les habilitats amb més marge de millora.':'El sistema ha actualitzat el teu itinerari. Les respostes encertades al segon intent compten parcialment.'}</p><div class="skill-list">${skillRows()}</div><div class="callout" style="margin-top:22px"><strong>Pròxim pas:</strong> ${nextGoal()}</div><div class="hero-actions" style="margin-top:22px"><button class="btn btn-primary" data-action="adaptive">Començar una sessió</button><button class="btn btn-secondary" data-view="progress">Veure el progrés</button></div></article></section>`}
function diagnosticLevel(m){const avg=Object.values(m).reduce((a,b)=>a+b,0)/4;if(avg<35)return 1;if(avg<50)return 2;if(avg<63)return 3;if(avg<75)return 4;if(avg<87)return 5;return 6}
function weakestKey(){return Object.entries(state.mastery).sort((a,b)=>a[1]-b[1])[0][0]}
function weakestName(){return SKILLS[weakestKey()].name}
function levelName(n){return["","Pistes clares","Connecta dades","Detectiu del text","Visió global","Proves i arguments","Mirada crítica"][n]}
function nextGoal(){return{locate:"localitzar informació explícita dispersa.",infer:"explicar causes i intencions a partir de pistes.",integrate:"connectar idees de diferents parts del text.",reflect:"valorar la intenció i la fiabilitat d’una font."}[weakestKey()]}
function openLibrary(){bankOpen=true;setView('practice',false);requestAnimationFrame(()=>document.querySelector('#bank-panel')?.scrollIntoView({block:'start',behavior:'smooth'}))}
function bindGeneral(){document.querySelectorAll("[data-view]").forEach(b=>b.onclick=()=>setView(b.dataset.view));document.querySelectorAll("[data-action]").forEach(b=>{if(b.dataset.action==="diagnostic")b.onclick=()=>{document.querySelector("#app").innerHTML=diagnosticIntro();bindGeneral()};if(b.dataset.action==="start-diagnostic")b.onclick=startDiagnostic;if(b.dataset.action==="adaptive")b.onclick=()=>startReading(null,true);if(b.dataset.action==="open-library")b.onclick=openLibrary;if(b.dataset.action==="toggle-bank")b.onclick=()=>{bankOpen=!bankOpen;render()}});bindBank();registerWebMCP()}
function bindBank(){const panel=document.querySelector("#bank-panel");if(!panel)return;panel.querySelector("#bank-search").oninput=e=>{bankQuery=e.target.value;bankPage=0;refreshBank(true)};panel.querySelector("#bank-type").onchange=e=>{bankType=e.target.value;bankPage=0;refreshBank()};panel.querySelectorAll("[data-reading]").forEach(b=>b.onclick=()=>startReading(b.dataset.reading));panel.querySelector('[data-action="prev-page"]').onclick=()=>{bankPage--;refreshBank()};panel.querySelector('[data-action="next-page"]').onclick=()=>{bankPage++;refreshBank()}}
function refreshBank(focusSearch=false){const panel=document.querySelector("#bank-panel");if(!panel)return;panel.outerHTML=bankMarkup();bindBank();if(focusSearch){const input=document.querySelector("#bank-search");input.focus();input.setSelectionRange(input.value.length,input.value.length)}}
function registerWebMCP(){const ctx=document.modelContext;if(!ctx?.registerTool||window.__comprenTools)return;window.__comprenTools=true;const reg=t=>{try{Promise.resolve(ctx.registerTool(t)).catch(()=>{})}catch{}};reg({name:"get_learning_progress",title:"Consultar progrés lector",description:"Mostra el nivell actual i el domini de cada habilitat lectora.",inputSchema:{type:"object",properties:{},additionalProperties:false},annotations:{readOnlyHint:true,untrustedContentHint:false},execute:()=>({level:state.level,mastery:state.mastery,totalAnswered:state.totalAnswered,nextGoal:nextGoal()})});reg({name:"start_recommended_reading",title:"Començar lectura recomanada",description:"Obri una sessió de pràctica triada segons l’habilitat més feble i el nivell actual.",inputSchema:{type:"object",properties:{},additionalProperties:false},annotations:{readOnlyHint:false,untrustedContentHint:false},execute:()=>{startReading(null,true);return{started:true,title:activity.reading.title,questions:activity.questions.length,focus:weakestName()}}})}
document.addEventListener("click",e=>{const b=e.target.closest(".brand");if(b)setView("home")});
render();
